# Generated by Django 2.0.3 on 2019-07-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpuApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpu',
            fields=[
                ('avg', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cpuInfo',
            },
        ),
        migrations.CreateModel(
            name='disk',
            fields=[
                ('avgused', models.FloatField(primary_key=True, serialize=False)),
                ('avgaval', models.FloatField(primary_key=True)),
            ],
            options={
                'db_table': 'diskInfo',
            },
        ),
        migrations.CreateModel(
            name='mem',
            fields=[
                ('avgused', models.FloatField(primary_key=True, serialize=False)),
                ('avgaval', models.FloatField(primary_key=True)),
            ],
            options={
                'db_table': 'memInfo',
            },
        ),
        migrations.CreateModel(
            name='real',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
