# Generated by Django 2.0.3 on 2019-07-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpuApp', '0002_auto_20190704_0908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='real',
        ),
    ]
